### ISSUE TITLE
About samples_per_gpu

### ISSUE THREAD

**Issue by hyalvin** [Czm369/MixPL#13]
Hi, thanks to the nice work first.
I wanna know that if we can set `samples_per_gpu` to values except for 5?
And also, can we set the samples number from labeled and unlabeled datasets, which is 1 and 4 respectively in your default setting, to other ratios like 3 and 2?
Is there any constrains for setting these hyper-parameters? 

Hopes for your quick reply, thanks!

**Comment by Czm369** [comment]
Of course. It is best to set `batch_size=labeled+unlabeled`, and the weights also need to tune between `1:1` and `1:2`. Because there exists a balance between labeled gradient and pseudo-labled gradient.

**Comment by hyalvin** [comment]
So. there is no constrains on these parameters to make the algorithms work and the current settings is for optimal performance?

Also, you said `and the weights also need to tune between 1:1 and 1:2`, but why the default setting is 1 and 4, which make a weight `1:4`?

Hopes for your quick reply, thanks!

**Comment by Czm369** [comment]
The ratio of labeled and unlabeled images in each batch can change, but in general, the number of unlabeled images is greater than the number of labeled images, but the weight of a single unlabeled image is no higher than the weight of a single labeled image

**Comment by hyalvin** [comment]
Got it, thanks a lot!
