### ISSUE TITLE
How to understand Figure 1 in the paper?

### ISSUE THREAD

**Issue by heha102** [Czm369/MixPL#18]
Why do different methods always differ by 2map between the same detector, and the dots on the graph are not consistent?
![image](https://github.com/user-attachments/assets/b2744be1-b7e8-467b-bc18-4cb79200df7a)

**Comment by Czm369** [comment]
The inside numbers represent the precision of DetMeanTeacher, the outside numbers are the coordinates of reference, the indicators of MixPL are not written out on the graph.
